FROM python:3.11-alpine

ENV first_name='Xolmirza'
ENV last_name='Abubakirov'
ENV age=18


# Folder yaratildi
WORKDIR /abc

# python faylni ko'chirish

COPY main.py /abc/

CMD [ "python", "/abc/main.py" ]